name: New Feature Idea/Request Form
description: Suggest a new feature 
title: '[FEATURE]'
labels: enhancement
body: 
  - type: dropdown
    id: feature_type
    attributes:
      label: Why is this feature proposed?
      options:
        - New Feature
        - Idea Proposal
        - Feature to resolve existing issue
      multiple: true
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Summary of the feature
      placeholder: A concise description of what is being prosposed
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Who benefits from this solution? 
      placeholder: Please describe the possible pros and cons on implementing this feature
    validations:
      required: true
    
  - type: textarea
    attributes:
      label: Expected outcome/ Requirements for feature completion
      placeholder: Describe what the expected outcome of the feature will be
    validations:
      required: false
    
  - type: textarea
    attributes:
      label: Alternatives
      placeholder: | 
        Were there alternative solutions considered?
        Can be other implementation solutions or external tools that can accomplish the ask
    validations:
      required: false
    
  - type: textarea
    attributes:
      label: Anything else?
      placeholder: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
